### PR TITLE
feat: tree changes

### PR DESCRIPTION
**Pull request by FL33TW00D**
Perhaps it's not your style, but thought I'd raise since I spent this morning messing with it.

### CODE REVIEW

**Comment by kali** [comment]
Is this more than some syntax tweaks ? Is this fixing somethis I've missed ?

**Comment by FL33TW00D** [comment]
> Is this more than some syntax tweaks ? Is this fixing something I've missed ?

Behaviour is all the same - just syntax!

**Comment by kali** [comment]
All right, I'm a tad curious to know what compelled you to look into this terrible code, but thanks for trying to make it less terrible.

**Comment by kali** [comment]
@FL33TW00D FYI, I missed two clippy warnings yesterday when I merged your PR. Just fixed them. See #1130 .

**Pull request merged**
