### PR TITLE
WIP: Use external C implementation for f16 dot product

### PR DESCRIPTION
**Pull request by VariantXYZ**
Ping #916

### CODE REVIEW

**Comment by VariantXYZ** [comment]
The build failures are a bit of a pain:

> https://clang.llvm.org/docs/LanguageExtensions.html#half-precision-floating-point

Not sure how to best handle this. Maybe just building conditionally with fp16 support is available on the target at compile-time?

**Comment by kali** [comment]
About the build issues, well, we can't assume we'll always have clang.

* So, first, in build.rs, we must only try to compile this code if the c compiler is clang.
* we must inform from build.rs the main Rust code whether the clang-optimized function is available.
* we must have an alternative fallback Rust function, which will be set by default on Ops.
* finally if the clang-optimized function is available we can overwrite the default

**Comment by kali** [comment]
This is great news. Keep me posted on your progress :)

**Comment by VariantXYZ** [comment]
Closed the PR. I think the change in the half-crate is the correct way to go.

I'll see if I can fit it in to that mold somehow.

**Pull request closed without merging**
