### PR TITLE
Bump ndarray from 0.15.3 to 0.16

### PR DESCRIPTION
**Pull request by Dirreke**
Blocked by https://github.com/jturner314/ndarray-npy/pull/73

### CODE REVIEW

**Comment by Dirreke** [comment]
Should I rename it to `into_shape_with_order`, which is the same as `ndarray`(https://github.com/rust-ndarray/ndarray/pull/1310)
https://github.com/sonos/tract/blob/fedab8df3b800482e9a398dc919656674b058518/data/src/tensor.rs#L518C1-L518
```rust
    pub fn into_shape(mut self, shape: &[usize]) -> TractResult<Tensor> {
```

**Comment by kali** [comment]
> Should I rename it to `into_shape_with_order`, which is the same as `ndarray`([rust-ndarray/ndarray#1310](https://github.com/rust-ndarray/ndarray/pull/1310))
> 
> https://github.com/sonos/tract/blob/fedab8df3b800482e9a398dc919656674b058518/data/src/tensor.rs#L518-L518

No reason to. Tensors in tract are always in "natural order" (row major, but generalized, axes with bigger strides come first).

**Comment by Dirreke** [comment]
Hi~ Shall we rerun CI?

**Comment by kali** [comment]
> Hi~ Shall we rerun CI?

Sure, let's see where we are. :) But we need to address the ndarray-npy situation before moving further (as in merge).

**Comment by barakugav** [comment]
@Dirreke @kali `ndarray-npy` 0.9.1 was release, can we push this PR forward? looking forward to it

**Comment by Dirreke** [comment]
@kali Let's rerun CI. Thanks

**Comment by kali** [comment]
thanks for your contibution!

**Pull request merged**
