### PR TITLE
Refactored the fix for NNEF gzip file detection

### PR DESCRIPTION
**Pull request by russellwmy**
I reviewed the code again, developer is still able to call the `proto_model_for_read` method with reader parameter. In this case the gzip detection is skipped. I moved the check inside `proto_model_for_read`, so that we can avoid this issue.

BTW, do you have `mobilenet_v2_1.0.onnx.nnef.tar` file for testing. I tried to create one with  decompress and compress again with tar command. But it give me this error: `Error: Wrong magic number`.

### CODE REVIEW

**Comment by kali** [comment]
Good call moving the check at the proto_model place.

you should get the model in raw tar form by just doing: `gunzip mobilenet_v2_1.0.onnx.nnef.tar.gz`

**Comment by russellwmy** [comment]
@kali  I tested both `tar` and `tgz`. In both cases, the example is looking good. I changed a better name for new variables.
Please review the PR.

**Review by kali — APPROVED** [review]

**Comment by kali** [comment]
This looks good... Can we just have it squashed and rebased against the current main ?

**Comment by russellwmy** [comment]
@kali  Finally, finish your change requests. it took me sometime to learn rebase.
I think it all good now.

**Comment by kali** [comment]
Aha, yeah rebase is tricky, very powerful and a bit scary. You will use it again :)

**Pull request merged**
