### PR TITLE
Add coordinate_transformation asymmetric mode

### PR DESCRIPTION
**Pull request by chriamue**
Followed this pseudocode: https://github.com/onnx/onnx/blob/master/docs/Operators.md#attributes-72

### CODE REVIEW

**Comment by kali** [comment]
Hello ! Thanks for the contribution.

Code looks good. Can you try to see if it validates any test case in the onnx test suite ?

`cd harness/onnx-test-suite; cargo run`

If new tests are passing, they should be added to some `node-*.txt` files. If they are some, a `cargo run --all-features` will try to add them to all `*.txt` files, and you can commit theses changes.

If no new test is validated, can you just tell me if you were able to run a new model (yolo, maybe ?) and check their results ?

**Comment by kali** [comment]
OK, nice to get these, but they're not covering anything close to what we are trying to test. I guess they may be new test cases that appeared in the onnx repo.

Do you intend to pursue this and also implement `nearest` to make yolo work? If that is the case, we can just cover these resize use-cases by an integrated full-model test. The idea is to make a .npy file with input and expected ouput (obtained running the model from python in onnx runtime). Then we can use the command line to replay in tract and assert the result. If you go this way, don't put big assets under git, I'll do it one way or the other.

WDYT ?

**Comment by kali** [comment]
Some example for using the command line to test a model with a .npy bundle here. 
https://github.com/sonos/tract/blob/main/.travis/cli-tests.sh#L127 .

./target/release/tract $CACHEDIR/inceptionv1_quant.nnef.tar.gz \
    --nnef-tract-core \
    --input-bundle $CACHEDIR/inceptionv1_quant.io.npz \
    run \
    --assert-output-bundle $CACHEDIR/inceptionv1_quant.io.npz \

So for you, it would be something like `cd cli; cargo run yolo.onnx --input-bundle io.npz run --assert-output-bundle io.npz`. You need to match tensor names in the bundle with input and output names in the network.

**Comment by chriamue** [comment]
Hi, I tried also implementing nearest in this branch https://github.com/chriamue/tract/blob/9d55bf5f775305e2049a10b697e3bbb345a4c8d2/onnx/src/ops/resize.rs#L18

but running the [yolo_v3 model](https://github.com/onnx/models/tree/master/vision/object_detection_segmentation/tiny-yolov3)
results in sth. like Unimplemented(Loop) if I remember.

I downgraded to [yolo_v2 model](https://github.com/onnx/models/tree/master/vision/object_detection_segmentation/tiny-yolov2)
in this project https://github.com/lenna-project/yolo-plugin/blob/8e5316c2c9947ee29d2dcdd1c1b4aa3deb56a71a/src/lib.rs#L99 .
The model loads and runs, but I am still working on the processing of the output to be able to evaluate the output.

**Comment by kali** [comment]
All right, let's try to make yolo v2 work. Loop will be an absolute pain to implement, so let's try to lock the resize changes like that before investigating Loop.

**Comment by chriamue** [comment]
The sizes are wrong, but the positions are promising.

**Comment by kali** [comment]
I'm not 100% sure about sheep, and bottle is definitely wrong, but... well close enough :)

**Comment by kali** [comment]
Ho, and apparently there's a cow too :)

**Comment by chriamue** [comment]
> Some example for using the command line to test a model with a .npy bundle here. https://github.com/sonos/tract/blob/main/.travis/cli-tests.sh#L127 .
> 
> ./target/release/tract $CACHEDIR/inceptionv1_quant.nnef.tar.gz --nnef-tract-core --input-bundle $CACHEDIR/inceptionv1_quant.io.npz run --assert-output-bundle $CACHEDIR/inceptionv1_quant.io.npz \
> 
> So for you, it would be something like `cd cli; cargo run yolo.onnx --input-bundle io.npz run --assert-output-bundle io.npz`. You need to match tensor names in the bundle with input and output names in the network.

What would the best way to generate the input bundle io.npz?

```sh
~/temp/tract/cli$ cargo run tinyyolov2-7.onnx --input-bundle io.npz run --assert-output-bundle io.npz
    Finished dev [unoptimized + debuginfo] target(s) in 0.09s
     Running `/home/chriamue/temp/tract/target/debug/tract tinyyolov2-7.onnx --input-bundle io.npz run --assert-output-bundle io.npz`
[2022-01-09T05:43:29.150752662Z WARN  tract_onnx::model] ONNX operator for your model is 7, tract is tested against operator set 9, 10, 11 and 12 only. Your model may still work so this is not a hard fail.
[2022-01-09T05:43:29.182944753Z ERROR tract] No such file or directory (os error 2)
```

**Comment by chriamue** [comment]
I generated the io.npz file this way:
```python
import onnx
import onnxruntime
model_file = 'assets/tinyyolov2-7.onnx'
session = onnxruntime.InferenceSession(model_file, None)
input_name = session.get_inputs()[0].name
output_name = session.get_outputs()[0].name
img = cv2.imread("assets/dog.jpg")
img = cv2.resize(img, dsize=(416, 416), interpolation=cv2.INTER_AREA)
img.resize((1, 3, 416, 416))
import json
import cv2
data = json.dumps({'data': img.tolist()})
data = np.array(json.loads(data)['data']).astype('float32')
result = session.run([output_name], {input_name: data})
import numpy as np
np.savez("io.npz", image=data, grid=result[0])
```

Tract now runs without output:
```sh
~/temp/tract/cli$ cargo run tinyyolov2-7.onnx --input-bundle io.npz run --assert-output-bundle io.npz
    Finished dev [unoptimized + debuginfo] target(s) in 0.08s
     Running `/home/chriamue/temp/tract/target/debug/tract tinyyolov2-7.onnx --input-bundle io.npz run --assert-output-bundle io.npz`
[2022-01-09T07:06:07.907088585Z WARN  tract_onnx::model] ONNX operator for your model is 7, tract is tested against operator set 9, 10, 11 and 12 only. Your model may still work so this is not a hard fail.
```

**Comment by kali** [comment]
So far so good. I think we just need to make sure that tract finds the output in the bundle. (Off the top of my head, I'm not 100% sure tract will not ignore the check if the names do not match.)

We can add a -v to the command line (use -- to make sure cargo does not eat the -v).

```cargo run -- -v tinyyolov2-7.onnx --input-bundle io.npz run --assert-output-bundle io.npz```

You should see a line like this: 
`2022-01-09T09:53:07.335398276Z INFO  tract::utils] Checked output #0, ok.`

If we have the line, then I guess the io.npz is pretty small (<1M right ?). If that is the case, and the image you used is not encumbered by copyright, create a new folder `onnx/test_cases/yolo2` and put the io.npz in there. Adds a vars.sh just like the one in transformer-mlm. Also please tell me where to the right tinyyolo2 so I can put it in tract ci s3 bucket, the run_all script should take it from there...

**Comment by chriamue** [comment]
Yes the model did run.

```sh
cargo run -- -v tinyyolov2-7.onnx --input-bundle io.npz run --assert-output-bundle io.npz
[2022-01-09T10:22:50.218661842Z INFO  tract::params] Model Fs("tinyyolov2-7.onnx") loaded
[2022-01-09T10:22:50.218715186Z INFO  tract] Resource usage model loaded: vsz:115281920 rsz:87695360 rszmax:172335104
[2022-01-09T10:22:50.220926199Z INFO  tract::params] Will stop at before-optimize
[2022-01-09T10:22:50.220947451Z INFO  tract::params] Running 'analyse'
[2022-01-09T10:22:53.790210174Z INFO  tract] Resource usage after analyse: vsz:117436416 rsz:93765632 rszmax:172335104
[2022-01-09T10:22:53.790226289Z INFO  tract::params] Running 'incorporate'
[2022-01-09T10:22:57.366553762Z INFO  tract] Resource usage after incorporate: vsz:117440512 rsz:93765632 rszmax:172335104
[2022-01-09T10:22:57.366568554Z INFO  tract::params] Running 'type'
[2022-01-09T10:23:04.439650109Z INFO  tract] Resource usage after type: vsz:117440512 rsz:93765632 rszmax:172335104
[2022-01-09T10:23:04.439663722Z INFO  tract::params] Running 'declutter'
[2022-01-09T10:23:04.459549303Z INFO  tract] Resource usage after declutter: vsz:117440512 rsz:93765632 rszmax:172335104
[2022-01-09T10:23:04.459569113Z INFO  tract::params] Running 'before-optimize'
[2022-01-09T10:23:04.459586429Z INFO  tract] Resource usage after before-optimize: vsz:117440512 rsz:93765632 rszmax:172335104
[2022-01-09T10:23:04.459593090Z INFO  tract::params] Model ready
[2022-01-09T10:23:04.459610368Z INFO  tract] Resource usage model ready: vsz:117440512 rsz:93765632 rszmax:172335104
[2022-01-09T10:23:04.459911443Z INFO  tract::tensor] Using fixed input for input called image (1 turn(s))
[2022-01-09T10:23:04.478048342Z INFO  tract_linalg::x86_64_fma] mmm_f32, sigmoid_f32, tanh_f32: x86_64/fma activated
[2022-01-09T10:23:04.478062929Z INFO  tract_linalg::x86_64_fma] mmm_i8_i8 and mmm_i8_i32: x86_64/avx2 activated
[2022-01-09T10:23:07.780886361Z INFO  tract::utils] Checked output #0, ok.
[2022-01-09T10:23:07.783479244Z INFO  tract] Resource usage done: vsz:62803968 rsz:44703744 rszmax:214646784
```

The model was taken here: [Tiny YOLOv2 62 MB](https://github.com/onnx/models/blob/master/vision/object_detection_segmentation/tiny-yolov2/model/tinyyolov2-7.onnx)

The image taken is original from [darknet](https://github.com/pjreddie/darknet) under the [DO WHAT THE FUCK YOU WANT TO PUBLIC LICENSE](https://github.com/pjreddie/darknet/blob/master/LICENSE.fuck)


The io.npz file is more than 2MB in size:
```sh
ls -l io.npz
2,1M io.npz
```

I named the model file in vars.sh as CACHE_FILES=tinyyolov2-7-model.onnx.

**Comment by kali** [comment]
Uploaded the model, hopefully at the right place, let's see what happens.

**Comment by kali** [comment]
Uploaded with a wrong file name, fixed it, rerunning.

**Comment by kali** [comment]
Ok, this one looks pretty good. Merging now.

**Pull request merged**
